### ISSUE TITLE
opam release

### ISSUE THREAD

**Issue by despairblue** [c-cube/cconv#16]
Hey thanks for working on this.

Would it be possible to release a new version to opam? 

The version on opam is 2 years old.

I'm trying to use this with dune and have the same problems that has been fixed [here](https://github.com/c-cube/cconv/pull/14). 

I actually only found that PR because I found an [IRC chat](https://irclog.whitequark.org/ocaml/2018-01-24) where @tizoc mentioned the same issue I have `Error: Cannot locate deriver cconv`. Only then I realized that I may be using an old version.

**Comment by c-cube** [comment]
I don't know if a new release would work well with ppx deriving, honestly. I haven't touched that in a while.

I can release the basic package if you want, but I think the ppx part should have its own opam file. Would you be interested in contributing to the deriver?

**Comment by despairblue** [comment]
> I can release the basic package if you want, but I think the ppx part should have its own opam file. Would you be interested in contributing to the deriver?

Sure, I'll try to make it working locally. Hope it's ok if I ask some questions if I get stuck :)

**Comment by c-cube** [comment]
This should work on master, I've looked, it's all in order and the tests pass.

```ocaml
utop [0]: #require "cconv-ppx";;
utop [1]: type foo = {x: int; y: string} [@@deriving cconv];;
val encode_foo : foo CConv.Encode.encoder = {CConv.Encode.emit = <fun>}
val decode_foo : foo CConv.Decode.decoder =
  {CConv.Decode.dec =
    {CConv.Decode.accept_unit = <fun>; accept_bool = <fun>;
     accept_float = <fun>; accept_int = <fun>; accept_int32 = <fun>;
     accept_int64 = <fun>; accept_nativeint = <fun>; accept_char = <fun>;
     accept_string = <fun>; accept_list = <fun>; accept_option = <fun>;
     accept_record = <fun>; accept_tuple = <fun>; accept_sum = <fun>}}
```

**Comment by c-cube** [comment]
https://github.com/ocaml/opam-repository/pull/13635
