### ISSUE TITLE
The deriver gets confused when trying to derive encoders for a type `t` referencing another type `t` from a different module.

### ISSUE THREAD

**Issue by tizoc** [c-cube/cconv#2]
(Original issue at: https://github.com/c-cube/ppx_deriving_cconv/issues/1)

To reproduce:

``` ocaml
module A = struct
  type t = int [@@deriving encode]
end

module B = struct
  type t = {
    a : A.t;
  } [@@deriving encode]
end
```

If I rename any of the types so that their name is not `t` it works, but whenever their names match (doesn't have to be `t` what matters is that they match), I get this error:

```
Error: This expression has type A.t = int
       but an expression was expected of type t
```

I don't know much about ppx, but after looking around a bit I think I figured out the fix:

The lines containing this (one in the encoder and another in the decoder)

``` ocaml
      | Some (name, used) when Longident.last lid=name ->
```

have to be changed to

``` ocaml
      | Some (name, used) when String.concat "." (Longident.flatten lid)=name ->
```

so that the full identifier (including the module) is used when comparing names.

I haven't tested it much, but applying that change to a local clone has fixed the issue for me.

**Comment by tizoc** [comment]
An a bit improved version which is what I'm using now (we know that if it belongs to a module already, it is not the same as the type being defined):

``` ocaml
      begin match self, lid with
      | Some (name, used), Lident liname when liname=name ->
```

**Comment by c-cube** [comment]
I'm really no expert at ppx, so I don't know the proper way of handling this. However, your change seems reasonable.

**Comment by c-cube** [comment]
if the change doesn't work for you, please re-open the issue
